name: Deploy Github Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check code style
        run: |
          yarn run fmt
          git --no-pager diff --exit-code

      - name: CI tests
        run: yarn run ava

      - name: Build scripts
        run: yarn run build-scripts

      - name: Fetch lingo words
        run: node --experimental-fetch dist/scripts/get-lingo-words.js

      - name: Type checking
        run: yarn tsc --noEmit

      - name: Build
        run: yarn run build-no-tests

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/www
